### PR TITLE
client: fixing test bug with hanging requests

### LINKED ISSUE #52: API calls take exactly the timeout of time
API calls made through the Unix socket appear to take exactly 500ms, which is the value of [`firecrackerRequestTimeout`](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/1585d53f793483c96d5d9058ca705d97d1b0558b/firecracker.go#L28).  I can observe this by manipulating the timeout in the [`runtime.ClientOperation`](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/1585d53f793483c96d5d9058ca705d97d1b0558b/client/client_transports_test.go#L50).

### PR DESCRIPTION
**Pull request by xibz**
Fixing test bug with hanging requests

Prior tests caused the HTTP client to hang waiting for a response. This
will now properly write a response and closing the request.

Fixes #52

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: client/client_transports_test.go [hunk 1]
```diff
@@ -1,42 +1,42 @@
...
-
-		data := string(buf[0:nr])
-		assert.Equal(t, expectedMessage, data, "expectedMessage received on socket is different than what was sent")
-		done <- true
+	listener, err := net.Listen("unix", socketPath)
+	if err != nil {
+		panic(err)
+	}
+
+	const expectedEndpoint = "/test-operation"
```
Comment (samuelkarp) [inline client/client_transports_test.go]: You've defined this as a const but you're only using it once.  Do you want to move it out of the scope of this function and use it here and in the `testOperation()` function?

File: client/client_transports_test.go [hunk 2]
```diff
@@ -1,42 +1,42 @@
...
+		Handler: http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
+			assert.Equal(t, expectedEndpoint, req.URL.String())
+			w.WriteHeader(http.StatusOK)
+			close(done)
+		}),
+	}
+
+	go server.Serve(listener)
+	defer func() {
+		listener.Close()
```
Comment (samuelkarp) [inline client/client_transports_test.go]: I think you should add `server.Shutdown()` above this line.
