### PR TITLE
Fixes issue where FifoLogWriter would hang

### LINKED ISSUE #143: Startup Hangs when using LogWriter
This pertains to PR #134 I worked on and it introduced the issue. 

When it was suggested to move `captureFifoToFile` to the handler, I forgot about the fact that if Firecracker is not started before we start listening on the log.fifo then `os.Open` in [captureFifoToFile](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/machine.go#L582) will block. Since we moved `captureFifoToFile` to a handler, this blocks the handlers which execute before we start Firecracker so it'll never unblock., shown [here](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/machine.go#L329-L334).

Mostly creating this issue to spark a discussion on the best place to put captureFifoToFile. The implementation before the above PR did not work with Jailer as the sdk jailer setup would change the path to the `LogFifo` in the config before we tried to listen on it.

I've outlined workflows from what I understand needs to happen in the case of jailer and plain firecracker.

Firecracker:
- Create `log.fifo` and `metric.fifo`
- Start Firecracker
- Configure logging and metrics via API
- Call `captureFifoToFile`

Jailer:
- Create `log.fifo` and `metric.fifo`
- Jailer chroot for vm setup
- Hard link `log.fifo` and `metric.fifo` into jailer chroot for VM
- Jailer start Firecracker
- Configure logging and metrics via API
- Call `captureFifoToFile` on original `log.fifo` path (not hard linked)

### PR DESCRIPTION
**Pull request by xibz**
Prior to this fix the FifoLogWriter would hang the process due to
waiting for the fifo to be connected to firecracker when attempting to
open the fifo. This fix wraps the capture fifo method in a goroutine.

Signed-off-by: xibz <impactbchang@gmail.com>

Fixes #143 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: handlers.go [hunk 1]
```diff
@@ -152,9 +152,13 @@ var CreateLogFilesHandler = Handler{
 		)
 
 		if m.Cfg.FifoLogWriter != nil {
-			if err := captureFifoToFile(m.logger, logFifoPath, m.Cfg.FifoLogWriter); err != nil {
-				m.logger.Warnf("captureFifoToFile() returned %s. Continuing anyway.", err)
-			}
+			// We wrap this in a goroutine since opening the fifo queue will block
+			// until the fifo has been connected when starting firecracker
+			go func() {
+				if err := captureFifoToFile(m.logger, logFifoPath, m.Cfg.FifoLogWriter); err != nil {
```
Comment (xibz) [inline handlers.go]: There is a goroutine already in `captureFifoToFile`. It may be best to just remove the one in `captureFifoToFile` and make `captureFifoToFile` to be expected to be ran in a goroutine.

File: handlers.go [hunk 2]
```diff
@@ -152,9 +152,13 @@ var CreateLogFilesHandler = Handler{
 		)
 
 		if m.Cfg.FifoLogWriter != nil {
-			if err := captureFifoToFile(m.logger, logFifoPath, m.Cfg.FifoLogWriter); err != nil {
-				m.logger.Warnf("captureFifoToFile() returned %s. Continuing anyway.", err)
-			}
+			// We wrap this in a goroutine since opening the fifo queue will block
+			// until the fifo has been connected when starting firecracker
```
Comment (sipsma) [inline handlers.go]: I just did an experiment to see what happens when:
1. A fifo is created
2. The fifo is attempted to be opened w/ `O_RDONLY` (causing the open call to block, as expected)
3. The fifo is then unlinked before a writer opens the other side

The behavior I saw, sadly, was that the open `O_RDONLY` did not get unblocked when the fifo was unlinked.

I think this is a problem because this could actually happen with the current code if `captureFifoToFile` is blocked on the open call, something else goes wrong with VM creation causing the create to fail and the fifos to be unlinked before the VMM opens them for reading on the other side. In this case, I think we would end up having a goroutine eternally blocked waiting on the open call.

Here's the code I tested with:
```
package main

import (
        "os"
        "syscall"
        "time"
)

func main() {
        err := syscall.Mkfifo("fifo", 0700)
        if err != nil {
                panic(err)
        }

        go func() {
                time.Sleep(3*time.Second)
                err := syscall.Unlink("fifo")
                if err != nil {
                        panic(err)
                }
        }()

        _, err = os.OpenFile("fifo", os.O_RDONLY, 0600)
        if err != nil {
                panic(err)
        }
}
```

Comment (sipsma) [reply handlers.go]: As far as possible fixes, maybe one thing to look into is containerd's standalone `fifo` package: https://github.com/containerd/fifo

I believe it allows you to use a `context` object to control the opening of FIFOs, which could be helpful here.

Comment (xibz) [reply handlers.go]: Bah, that sucks. I do have another solution but it requires a little bit more work, but should be more preferable imo

Comment (nmeyerhans) [reply handlers.go]: > The behavior I saw, sadly, was that the open `O_RDONLY` did not get unblocked when the fifo was unlinked.
> 

This is not surprising. The named FIFO behaves just like any other file when it's unlinked: the directory entry is removed, and the link count decremented, but processes with open file descriptors are not impacted.

I think this problem comes down to inadequate management of filesystem resources in two different contexts: inside the jail and outside the jail. AIUI, the logic before the jailer change was correct, we just lost some state when we overwrote the configuration with the jailed paths for the FIFOs. I think we might want to provide a context-aware abstraction around file paths within the jail, allowing us to identify the appropriate path from either context.

Comment (sipsma) [reply handlers.go]: > This is not surprising. The named FIFO behaves just like any other file when it's unlinked: the directory entry is removed, and the link count decremented, but processes with open file descriptors are not impacted.

The part that surprises me is that AFAIK no process actually has the file descriptor open when you run that example I pasted. There is a process trying to open the fifo, but the fifo is unlinked and not opened by anything else I'm aware of. That seems bizarre but maybe it's the expected behavior.

File: jailer.go [hunk 3]
```diff
@@ -358,6 +358,7 @@ func jail(ctx context.Context, m *Machine, cfg *Config) error {
 
 	m.cmd = builder.Build(ctx)
 
+	m.Handlers.FcInit = m.Handlers.FcInit.Swap(createBootstrapLoggingHandler(m.Cfg.LogFifo))
```
Comment (sipsma) [inline jailer.go]: I'm not super familiar with this aspect of the gosdk, but would it make more sense to put this swap in the call to `ChrootStrategy.AdaptHandlers` call below? On the surface `AdaptHandlers` seems like the right place to update the bootstrapLoggingHandler's log fifo path.

File: handlers.go [hunk 4]
```diff
@@ -174,10 +168,37 @@ var BootstrapLoggingHandler = Handler{
...
+			if err := captureFifoToFile(m.logger, m.Cfg.LogFifo, m.Cfg.FifoLogWriter); err != nil {
+				m.logger.Warnf("captureFifoToFile() returned %s. Continuing anyway.", err)
+			}
+		}
+
 		return nil
 	},
 }
 
+func createBootstrapLoggingHandler(logFifo string) Handler {
```
Comment (sipsma) [inline handlers.go]: Would it make sense to above this function do:
```
var BootstrapLoggingHandler = Handler{
  Name: BootstrapLoggingHandlerName,
  Fn: func(ctx context.Context, m *Machine) error {
    return createBootstrapLoggingHandler(m.Cfg.LogFifo)
  },
}
``` 

in order to dupe less code?

File: handlers.go (hunk 2 above)
Comment (nmeyerhans) [reply handlers.go]: Yeah, POSIX specifies that open() with O_RDONLY will block forever if there isn't a writer. Once the syscall has started, there isn't really a way to short-circuit it if the file disappears. The check for existence has already succeeded and doesn't run again.

If you change your test code to add a second call to OpenFile() with os.O_WRONLY in the goroutine after the sleep, your program will run to completion.

One possibility to avoid blocking would be to add `syscall.O_NONBLOCK` to the open flags, and then retry the operation several times in case open fails with `ENXIO`.

File: jailer.go (hunk 3 above)
Comment (xibz) [reply jailer.go]: Changed to just how default handlers are constructed

File: handlers.go (hunk 4 above)
Comment (xibz) [reply handlers.go]: Also changed

File: handlers.go [hunk 5]
```diff
@@ -151,31 +151,33 @@ var CreateLogFilesHandler = Handler{
...
-			m.logger.Warnf("setupLogging() returned %s. Continuing anyway.", err)
-		} else {
-			m.logger.Debugf("setup logging: success")
-		}
+func createBootstrapLoggingHandler(logFifo string) Handler {
+	return Handler{
+		Name: BootstrapLoggingHandlerName,
+		Fn: func(ctx context.Context, m *Machine) error {
+			if err := m.setupLogging(ctx); err != nil {
+				m.logger.Warnf("setupLogging() returned %s. Continuing anyway.", err)
```
Comment (sipsma) [inline handlers.go]: If `setupLogging` returns an error, we should probably return from the function (even if we only log the error and return nil). Otherwise, we can continue on from here to the `captureFifoToFile` call below and get blocked again due to `setupLogging` failing.

Is there any expected reason for `setupLogging` to fail? Would it just be simpler to return any error from it?

Comment (xibz) [reply handlers.go]: Fixed! Discussed offline but what was decided was to return nil if an error occurs, that we avoid the file potentially being blocked by open.

File: handlers_test.go [hunk 6]
```diff
@@ -663,76 +660,6 @@ func TestHandlers(t *testing.T) {
 	}
 }
 
-func TestCreateLogFilesHandler(t *testing.T) {
```
Comment (xibz) [inline handlers_test.go]: This test provides inconsistent results due to the handler now being asynchronous on opening the fifo. However, I realized that this test is testing the fifo writer, which we already have a test for. With that I decided to delete it.

**Comment by cpheps** [comment]
I was wondering if there is a timeline on this PR? We would very much like to get the fixes in this PR and #147 into or project.

**Comment by xibz** [comment]
Hey @cpheps, thank you for your patience! I am just waiting on one additional approval before I merge this in. I will go ahead and ping a couple folks to take a look at this, but we will look at this as soon as we can.

File: machine.go [hunk 7]
```diff
@@ -579,11 +579,16 @@ func (m *Machine) setupLogging(ctx context.Context) error {
...
 	// to write its contents to a file.
-	fifoPipe, err := os.OpenFile(fifoPath, os.O_RDONLY, 0600)
+	fd, err := syscall.Open(fifoPath, syscall.O_RDONLY|syscall.O_NONBLOCK, 0600)
 	if err != nil {
 		return fmt.Errorf("Failed to open fifo path at %q: %v", fifoPath, err)
 	}
 
+	fifoPipe := os.NewFile(uintptr(fd), fifoPath)
+	if fifoPipe == nil {
+		return fmt.Errorf("Invalid file descriptor: %v", err)
```
Comment (kzys) [inline machine.go]: `os.NewFile()` doesn't set `err`. So we shouldn't include err in the error message since it would be always nil.

File: machine_test.go [hunk 8]
```diff
@@ -250,6 +256,10 @@ func TestJailerMicroVMExecution(t *testing.T) {
 	}
 
 	m.StopVMM()
+
+	info, err := os.Stat(fifoWriterPath)
```
Comment (samuelkarp) [inline machine_test.go]: Why are you stating the writer here?

File: machine.go (hunk 7 above)
Comment (xibz) [reply machine.go]: Fixed!

File: handlers.go (hunk 2 above)
Comment (samuelkarp) [reply handlers.go]: @xibz Are you planning to add the retries that @nmeyerhans suggested?

File: machine_test.go (hunk 8 above)
Comment (xibz) [reply machine_test.go]: just to ensure that the fifo was actually created. Just want to ensure that that logic is correct.

**Comment by xibz** [comment]
> Can you add a test for captureFifoToFile (just by itself, not with anything else) testing that it can open a fifo that hasn't been opened for write yet, and then start actually capturing the content once the fifo is opened for write? I don't see that covered in the tests here.

There is already a test that does that, `TestCaptureFifoToFile`.

File: machine_test.go (hunk 8 above)
Comment (samuelkarp) [reply machine_test.go]: You're creating the fifo in the test (not the code under test) on line 150.  Why do you then need to assert that it's created?

(Stat doesn't tell you anything about the contents, either.)

**Comment by samuelkarp** [comment]
> There is already a test that does that, `TestCaptureFifoToFile`.

`TestCaptureFifoToFile` opens the file for write (line 784) and writes to it (line 789) prior to calling `captureFifoToFile` (line 806).  I'm asking you to call `captureFifoToFile` before opening the file for write and writing to it (to test that we're using `O_NONBLOCK` correctly).

File: handlers.go (hunk 2 above)
Comment (xibz) [reply handlers.go]: @samuelkarp - Not needed as we are opening with `O_RDONLY`.

From the man page
```
A process can open a FIFO in nonblocking mode.  In this case, opening
       for read-only succeeds even if no one has opened on the write side
       yet and opening for write-only fails with ENXIO (no such device or
       address) unless the other end has already been opened.
```

File: machine_test.go (hunk 8 above)
Comment (xibz) [reply machine_test.go]: Not created, just that something has been written to it

Comment (samuelkarp) [reply machine_test.go]: Okay, the name confused me.  This isn't a fifo, but the destination file where the data passed through a fifo ends up being written (in `captureFifoToFile`).  Can you change the name of this to reflect what it actually is?  Something like capturedLog?

Comment (xibz) [reply machine_test.go]: Done!

File: machine_test.go [hunk 9]
```diff
@@ -781,6 +801,18 @@ func TestCaptureFifoToFile(t *testing.T) {
 	}
 	defer os.Remove(fifoPath)
 
+	fifoLogPath := fifoPath + ".log"
```
Comment (samuelkarp) [inline machine_test.go]: nit: can you call this `logPath` or `destinationPath`?

File: machine_test.go [hunk 10]
```diff
@@ -781,6 +801,18 @@ func TestCaptureFifoToFile(t *testing.T) {
...
+	fifo, err := os.OpenFile(fifoLogPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
```
Comment (samuelkarp) [inline machine_test.go]: This isn't a fifo and shouldn't be called `fifo`.  This is your destination file, so call it `destination` or something like that.

File: machine_test.go [hunk 11]
```diff
@@ -781,6 +801,18 @@ func TestCaptureFifoToFile(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("Failed to create fifo file: %v", err)
```
Comment (samuelkarp) [inline machine_test.go]: This isn't a fifo.

File: machine_test.go [hunk 12]
```diff
@@ -781,6 +801,18 @@ func TestCaptureFifoToFile(t *testing.T) {
 	}
 	defer os.Remove(fifoPath)
 
+	fifoLogPath := fifoPath + ".log"
+	fifo, err := os.OpenFile(fifoLogPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0644)
+	if err != nil {
```
Comment (samuelkarp) [inline machine_test.go]: nit: You've got `assert` in this file already, so you might as well do `assert.NoError(t, err, "failed to create destination file")`.

File: machine_test.go [hunk 13]
```diff
@@ -781,6 +801,18 @@ func TestCaptureFifoToFile(t *testing.T) {
 	}
 	defer os.Remove(fifoPath)
```
Comment (samuelkarp) [inline machine_test.go]: You've changed the behavior of this test.  I think it'd be good to have tests for both behaviors rather than picking one over the other.

File: machine.go [hunk 14]
```diff
@@ -576,26 +576,35 @@ func (m *Machine) setupLogging(ctx context.Context) error {
 	return nil
 }
 
-func captureFifoToFile(logger *log.Entry, fifoPath string, fifo io.Writer) error {
+func captureFifoToFile(logger *log.Entry, captureFifoPath string, fifo io.Writer) error {
```
Comment (samuelkarp) [inline machine.go]: I think you actually do want `fifoPath`; it's the path of the fifo that we're reading.  You could change the `fifo io.Writer` to something like `w io.Writer` or `destination io.Writer`, which I think would be a lot more clear; the writer isn't a fifo and shouldn't be called one (we're reading a fifo, not writing one).

File: machine.go [hunk 15]
```diff
@@ -576,26 +576,35 @@ func (m *Machine) setupLogging(ctx context.Context) error {
...
 	}
 
-	logger.Debugf("Capturing %q to writer", fifoPath)
+	logger.Debugf("Capturing %q to writer", captureFifoPath)
 
-	// Uses a go routine to do a non-blocking io.Copy. The fifo
-	// file should be closed when the appication has finished, since
-	// the forked firecracker application will be closed resulting
-	// in the pipe to return an io.EOF
+	// Uses a goroutine to copy the contents of the fifo pipe to the captured log
```
Comment (samuelkarp) [inline machine.go]: "io.Writer"

Comment (xibz) [reply machine.go]: Fixed!

File: machine.go [hunk 16]
```diff
@@ -576,28 +576,37 @@ func (m *Machine) setupLogging(ctx context.Context) error {
 	return nil
 }
 
-func captureFifoToFile(logger *log.Entry, fifoPath string, fifo io.Writer) error {
+func captureFifoToFile(logger *log.Entry, fifoPath string, w io.Writer) error {
 	// create the fifo pipe which will be used
```
Comment (samuelkarp) [inline machine.go]: nit: "open the fifo"

File: machine.go (hunk 14 above)
Comment (xibz) [reply machine.go]: Fixed!

File: machine_test.go [hunk 17]
```diff
@@ -814,6 +834,45 @@ func TestCaptureFifoToFile(t *testing.T) {
...
+
+	go func() {
+		t := time.NewTicker(250 * time.Millisecond)
+		select {
+		case <-t.C:
+			f.Close()
+		}
+	}()
+
+	assert.NoError(t, err, "failed to stat file")
```
Comment (samuelkarp) [inline machine_test.go]: You're missing the actual stat here I think.  You could also use `ioutil.ReadFile` to get the file content and compare it to what you expect ("Hello world!").

File: machine.go (hunk 16 above)
Comment (xibz) [reply machine.go]: Fixed!

File: machine_test.go (hunk 17 above)
Comment (xibz) [reply machine_test.go]: doh, fixed.

Comment (xibz) [reply machine_test.go]: Also, to test the expected bytes, we'd need to write as soon as `captureFifoToFile` opens the file for reading, otherwise the bytes get lost.

Comment (xibz) [reply machine_test.go]: Alright, added the assert for expected bytes.

File: machine.go [hunk 18]
```diff
@@ -576,28 +576,37 @@ func (m *Machine) setupLogging(ctx context.Context) error {
...
 	go func() {
-		defer fifoPipe.Close()
+		defer func() {
+			if err := fifoPipe.Close(); err != nil {
+				logger.Warnf("Failed to close fifo pipe: %v", err)
+			}
+
+			if err := syscall.Unlink(fifoPath); err != nil {
+				logger.Warnf("Failed to unlink %s", fifoPath)
+			}
```
Comment (kzys) [inline machine.go]: - syscall.Unlink's error should be logged here.
- How about making both of them `Errorf`? Let's say the FIFO is being removed before reaching this line, wouldn't it indicate that we have a logic error somewhere, like cleaning up files twice?

Comment (xibz) [reply machine.go]: Sure, but I think warning is fine, since this isn't really a detrimental piece of code.

File: machine_test.go [hunk 19]
```diff
@@ -797,21 +819,90 @@ func TestCaptureFifoToFile(t *testing.T) {
...
-		t.Errorf("Failed to stat file: %v", err)
+	f, err := os.OpenFile(fifoPath, os.O_RDWR, 0600)
+	if err != nil {
+		t.Fatalf("Failed to open file, %q: %v", fifoPath, err)
 	}
+	expectedBytes := []byte("Hello world!")
+	f.Write(expectedBytes)
+	defer f.Close()
+
+	go func() {
```
Comment (samuelkarp) [inline machine_test.go]: nit: Can you change this to: `time.AfterFunc(250*time.Millisecond, func() { f.Close() })`?  https://golang.org/pkg/time/#AfterFunc

File: machine_test.go (hunk 11 above)
Comment (samuelkarp) [reply machine_test.go]: @xibz Can you fix this error message?

File: machine_test.go (hunk 19 above)
Comment (xibz) [reply machine_test.go]: Fixed

File: machine_test.go [hunk 20]
```diff
@@ -812,17 +812,14 @@ func TestCaptureFifoToFile(t *testing.T) {
 	defer f.Close()
 
 	go func() {
-		t := time.NewTicker(250 * time.Millisecond)
-		select {
-		case <-t.C:
-			f.Close()
-		}
+		t := time.AfterFunc(250*time.Millisecond, func() { f.Close() })
+		<-t.C
```
Comment (samuelkarp) [inline machine_test.go]: You don't need this.  You can just do `time.AfterFunc()` without the goroutine and without looking at `t.C`.

File: machine_test.go [hunk 21]
```diff
@@ -890,11 +887,8 @@ func TestCaptureFifoToFile_nonblock(t *testing.T) {
 	defer f.Close()
 
 	go func() {
-		t := time.NewTicker(250 * time.Millisecond)
-		select {
-		case <-t.C:
-			f.Close()
-		}
+		t := time.AfterFunc(250*time.Millisecond, func() { f.Close() })
```
Comment (samuelkarp) [inline machine_test.go]: Same here.

File: machine_test.go (hunk 19 above)
Comment (samuelkarp) [reply machine_test.go]: You don't need the goroutine and you don't need to drain `t.C`:

> AfterFunc waits for the duration to elapse and then calls f in its own goroutine. It returns a Timer that can be used to cancel the call using its Stop method.

Comment (xibz) [reply machine_test.go]: Sorry, thought you just wanted to swap the lines. Fixed.

**Comment by samuelkarp** [comment]
Can you fix your commit history?  You've got some issues in it:

* https://github.com/firecracker-microvm/firecracker-go-sdk/pull/145/commits/542e20c16bfa0c9361cd725be8e009e29f2a6fc6 is marked as a fixup of https://github.com/firecracker-microvm/firecracker-go-sdk/pull/145/commits/445c8758fd419ad9b36ec55723f88c1e6d4ec04c but should really be a fixup of https://github.com/firecracker-microvm/firecracker-go-sdk/pull/145/commits/08f6e0887b33db17ecc9bc55627ea9be9df9fff9
* https://github.com/firecracker-microvm/firecracker-go-sdk/pull/145/commits/61b460be8768fccd3ec629cc1bb1aaefa6ebf79d is marked as a fixup of https://github.com/firecracker-microvm/firecracker-go-sdk/pull/145/commits/445c8758fd419ad9b36ec55723f88c1e6d4ec04c but should really be a fixup of https://github.com/firecracker-microvm/firecracker-go-sdk/pull/145/commits/08f6e0887b33db17ecc9bc55627ea9be9df9fff9

**Comment by xibz** [comment]
> Can you fix your commit history? You've got some issues in it:

Done!
